name: Deploy Wegman's AI Chatbot resources to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Auto Deploy to Dev
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Dev
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG_DEV }}
          template: main.bicep
          parameters: environment=dev
          scope: resourcegroup
