name: Deploy Wegman's AI Chatbot resources to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    name: Auto Deploy to Dev
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_TENANT_ID }}
          tenant-id: ${{ env.ARM_CLIENT_ID }}
          subscription-id: ${{ inputs.subscription-id }}
          

      - name: Deploy to Dev
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ inputs.subscription-id }}
          resourceGroupName: ${{ inputs.resource-group-name }}
          template: main.bicep
          parameters: environment=dev
          scope: resourcegroup