name: Deploy Wegman's AI Chatbot resources to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - test
          - prod
      subscription-id:
        description: 'Azure Subscription ID'
        required: true
        type: string
      resourcegroup-id:
        description: 'Azure Resource Group Name'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}

    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}
    env:
      BUILD_VERSION: ${{ github.run_number }}-${{ github.run_id }}
    
    concurrency:
      group: deploy-${{ github.event.inputs.environment }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          tenant-id: ${{ env.ARM_TENANT_ID }}
          client-id: ${{ env.ARM_CLIENT_ID }}
          subscription-id: ${{ github.event.inputs.subscription-id }}

      - name: Deploy to ${{ github.event.inputs.environment }}
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ github.event.inputs.subscription-id }}
          resourceGroupName: ${{ github.event.inputs.resourcegroup-id }}
          template: infra/main.bicep
          parameters: environment=${{ github.event.inputs.environment }}
          scope: resourcegroup